nodeInfo: site.yaml
siteGlobal: ../site-global.yaml
templateDir: ../../../../ts-config/templates/
jsonschema: ../jsonschemas/schema-cnf.yaml
jsonschemaGlobal: ../jsonschemas/schema-global.yaml

files:
- template: pcg/1.19/values.yaml.jinja2
  target: values.yaml
- template: pcg/1.19/instantiate.json.jinja2
  target: instantiate.json
- template: common/snmp-config.json.jinja2
  target: snmp-config.json
- template: common/user-config.txt.jinja2
  target: user-config.txt
- template: pcg/1.19/pcg-config.txt.jinja2
  target: pcg-config.txt
- template: common/ddc-config.txt.jinja2
  target: ddc-config.txt
- template: common/network-policy/eric-pm-server-allow.yaml.jinja2
  target: network-policy/eric-pm-server-allow.yaml
- template: common/network-policy/eric-data-search-engine-allow.yaml.jinja2
  target: network-policy/eric-data-search-engine-allow.yaml
